<?php
require_once 'config/db.php';
if (!isLoggedIn()) { redirect('login.php'); }
$orderId = isset($_GET['id']) ? (int)$_GET['id'] : 0;
$stmt = $pdo->prepare("SELECT * FROM orders WHERE id = ? AND user_id = ?");
$stmt->execute([$orderId, $_SESSION['user_id']]);
$order = $stmt->fetch();
if (!$order) { redirect('orders.php'); }
$stmt = $pdo->prepare("SELECT * FROM order_items WHERE order_id = ?"); $stmt->execute([$orderId]); $items = $stmt->fetchAll();
$cartCount = getCartCount($pdo);
$stepOrder = ['pending'=>1,'confirmed'=>1,'preparing'=>2,'out_for_delivery'=>3,'delivered'=>4,'cancelled'=>0]; $currentStep = $stepOrder[$order['status']] ?? 0;
$etaLabels = ['pending'=>'About 30 minutes away','confirmed'=>'About 25 minutes away','preparing'=>'Being packed for you','out_for_delivery'=>'Arriving in about 8 minutes','delivered'=>'Delivered to your doorstep','cancelled'=>'This order was cancelled']; $eta = $etaLabels[$order['status']] ?? 'We are checking your delivery';
$steps = [['label'=>'Order confirmed','detail'=>'We received your basket'],['label'=>'Packing your picks','detail'=>'Freshness is being checked'],['label'=>'On its way','detail'=>'Your rider is heading over'],['label'=>'Delivered','detail'=>'Enjoy every good thing']];
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Track order #<?= $orderId ?> — Bari &amp; Saha</title><meta name="description" content="Track the delivery status of your Bari &amp; Saha grocery order."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Sora:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="css/store.css"></head><body>
    <nav class="navbar"><div class="container nav-inner"><a href="store.php" class="logo"><span class="logo-mark">B</span><div class="logo-info"><span class="logo-name">Bari <i>&amp;</i> Saha</span><span class="logo-tagline">Your neighbourhood market</span></div></a><div class="nav-actions"><a href="orders.php" class="nav-action-btn"><span class="nav-action-label">My orders</span></a><a href="cart.php" class="nav-cart-btn" id="navCartBtn"><span class="nav-cart-label">Cart</span><?php if ($cartCount > 0): ?><span class="cart-badge"><?= $cartCount ?></span><?php endif; ?></a></div></div></nav>
    <main class="tracking-page"><div class="container"><a class="tracking-back" href="orders.php">← All orders</a><section class="tracking-hero <?= $order['status'] === 'delivered' ? 'is-delivered' : '' ?>"><div><p class="eyebrow">ORDER #<?= $orderId ?></p><h1><?= $eta ?></h1><p>Placed <?= date('d M, h:i A', strtotime($order['ordered_at'])) ?> · <span class="order-status status-<?= $order['status'] ?>"><?= ucfirst(str_replace('_', ' ', $order['status'])) ?></span></p></div><div class="tracking-orb"><span><?= $order['status'] === 'delivered' ? '✓' : '↗' ?></span><small><?= $order['status'] === 'out_for_delivery' ? 'LIVE' : 'FRESH' ?></small></div></section><div class="tracking-layout"><section class="tracking-card"><h2>Delivery journey</h2><div class="tracking-timeline <?= $order['status'] === 'cancelled' ? 'is-cancelled' : '' ?>"><?php foreach ($steps as $index => $step): $number = $index + 1; $isDone = $currentStep >= $number; $isCurrent = $currentStep === $number; ?><div class="tracking-step <?= $isDone ? 'done' : '' ?> <?= $isCurrent ? 'current' : '' ?>"><span class="tracking-dot"><?= $isDone ? '✓' : $number ?></span><div><strong><?= $step['label'] ?></strong><p><?= $step['detail'] ?></p></div><?php if ($isCurrent && $order['status'] !== 'delivered'): ?><em>Now</em><?php endif; ?></div><?php endforeach; ?></div><?php if ($order['status'] === 'cancelled'): ?><p class="tracking-cancelled">This delivery was cancelled. You can still add the same items to your cart.</p><?php endif; ?></section><aside class="tracking-card delivery-card"><h2>Delivering to</h2><p class="delivery-address"><?= nl2br(sanitize($order['delivery_address'])) ?></p><span><?= sanitize($order['phone']) ?></span><hr><h3>Your basket</h3><?php foreach ($items as $item): ?><div class="tracking-item"><span><?= $item['product_emoji'] ?></span><p><?= sanitize($item['product_name']) ?><small><?= $item['quantity'] ?> × ₹<?= number_format($item['price']) ?></small></p><strong>₹<?= number_format($item['price'] * $item['quantity']) ?></strong></div><?php endforeach; ?><div class="tracking-total"><span>Total paid</span><strong>₹<?= number_format($order['total_amount']) ?></strong></div><button class="tracking-reorder" onclick="reorderOrder(<?= $orderId ?>, this)">Order this again <span>→</span></button></aside></div></div></main><div class="toast-container" id="toastContainer"></div><script src="js/store.js"></script>
</body></html>
